### ISSUE TITLE
Times not displaying correctly

### ISSUE THREAD

**Issue by Jeremy-Vidaurri** [TimH96/frog-champions#5]
Sometimes the decimal has a bunch of extra 0s as seen below. Example comes from [here](https://timh96.github.io/frog-champions/player.html?player=8dw5n19j)
![image](https://github.com/TimH96/frog-champions/assets/10247339/03eb53fb-6f9a-4af0-a825-cfb8c4324995)

**Comment by TimH96** [comment]
Just fixed it, thanks for pointing it out.
https://github.com/TimH96/frog-champions/commit/70c2200b6f596da6f75028d264f255fd716781b2
